### ISSUE TITLE
Crashes on OnCreate

### ISSUE THREAD

**Issue by fantasticrahulrai** [lapism/search#410]
Wasted few hours trying to add this library, crashes everytime, even when following all the instruction. Atleast include a sample project

**Comment by lapism** [comment]
- If there is a bug somewhere I need stacktrace from Android Studio
- README here should be enough
- I can't because the library is a submodule from my project. Maybe I will do another Sample repository in future.

**Comment by lapism** [comment]
Btw. I has been done with Java & Kotlin 1.8. Maybe that is the source of your problems.

**Comment by fantasticrahulrai** [comment]
Hi dear 
Thanks a lot for such a quick reply, I badly need this library in my project. I am sending the stacktrace, plz help

**Comment by fantasticrahulrai** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.cupcake.demo.dev/app.cupcake.demo.activites.ExploreActivity}: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
     Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:686)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at app.cupcake.demo.activites.ExploreActivity.onCreate(ExploreActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.widget.FrameLayout.LayoutParams
        at com.lapism.search.internal.SearchLayout.setMargins(SearchLayout.kt:136)
        at com.lapism.search.internal.SearchLayout.init(SearchLayout.kt:250)
        at com.lapism.search.widget.MaterialSearchView.<init>(MaterialSearchView.kt:32)
        at com.lapism.search.widget.MaterialSearchView.<init>(MaterialSearchView.kt:19)
        at com.lapism.search.widget.MaterialSearchView.<init>(Unknown Source:8)
        	... 28 more
W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.cupcake.demo.dev/app.cupcake.demo.activites.ExploreActivity}: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
    Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:686)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at app.cupcake.demo.activites.ExploreActivity.onCreate(ExploreActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.widget.FrameLayout.LayoutParams
        at com.lapism.search.internal.SearchLayout.setMargins(SearchLayout.kt:136)
        at com.lapism.search.internal.SearchLayout.init(SearchLayout.kt:250)
        at com.lapism.search.widget.MaterialSearchView.<init>(MaterialSearchView.kt:32)
        at com.lapism.search.widget.MaterialSearchView.<init>(MaterialSearchView.kt:19)
        at com.lapism.search.widget.MaterialSearchView.<init>(Unknown Source:8)

**Comment by fantasticrahulrai** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.cupcake.demo.dev/app.cupcake.demo.activites.ExploreActivity}: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
     Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:686)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at app.cupcake.demo.activites.ExploreActivity.onCreate(ExploreActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.widget.FrameLayout.LayoutParams
        at com.lapism.search.internal.SearchLayout.setMargins(SearchLayout.kt:136)
        at com.lapism.search.internal.SearchLayout.init(SearchLayout.kt:250)
        at com.lapism.search.widget.MaterialSearchView.<init>(MaterialSearchView.kt:32)
        at com.lapism.search.widget.MaterialSearchView.<init>(MaterialSearchView.kt:19)
        at com.lapism.search.widget.MaterialSearchView.<init>(Unknown Source:8)
        	... 28 more
W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.cupcake.demo.dev/app.cupcake.demo.activites.ExploreActivity}: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
    Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class com.lapism.search.widget.MaterialSearchView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:686)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at app.cupcake.demo.activites.ExploreActivity.onCreate(ExploreActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.widget.FrameLayout.LayoutParams
        at com.lapism.search.internal.SearchLayout.setMargins(SearchLayout.kt:136)
        at com.lapism.search.internal.SearchLayout.init(SearchLayout.kt:250)
        at com.lapism.search.widget.MaterialSearchView.<init>(MaterialSearchView.kt:32)
        at com.lapism.search.widget.MaterialSearchView.<init>(MaterialSearchView.kt:19)
        at com.lapism.search.widget.MaterialSearchView.<init>(Unknown Source:8)

**Comment by fantasticrahulrai** [comment]
Hi dear I have added the stacktrace, let me know if you need further specification about my project.

**Comment by lapism** [comment]
Your MainActivity layout is not a CoordinatorLayout right ? This can be a problem because MaterialSearchView implements CoordinatorLayout.Behavior.

**Comment by fantasticrahulrai** [comment]
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".activites.ExploreActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

    </com.google.android.material.appbar.AppBarLayout>

    <com.lapism.search.widget.MaterialSearchView
        android:id="@+id/materialSearchView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="0dp"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <co.lujun.androidtagview.TagContainerLayout
            android:id="@+id/tagContainer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="8dp"
            android:layout_marginTop="8dp"
            android:layout_marginEnd="8dp"
            android:layout_marginBottom="8dp"
            android:padding="10dp"

            app:container_background_color="#00000000"
            app:container_border_color="#3300ff00"
            app:container_border_radius="0dp"
            app:container_border_width="4dp"
            app:container_enable_drag="false"
            app:horizontal_interval="10dp"
            app:layout_constraintBottom_toTopOf="@+id/pullToRefresh"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:tag_clickable="true"
            app:tag_theme="random"
            app:vertical_interval="10dp" />

        <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
            android:id="@+id/pullToRefresh"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tagContainer">


            <ListView
                android:id="@+id/listview"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:clipToPadding="false"
                android:divider="@null"
                android:dividerHeight="4dp"
                android:padding="16dp"
                android:scrollbars="none" />


        </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>

        <com.cleveroad.androidmanimation.LoadingAnimationView
            android:id="@+id/animation"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:lav_backgroundColor="@android:color/black"
            app:lav_speedCoefficient="1.0"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tagContainer" />

    </androidx.constraintlayout.widget.ConstraintLayout>


</androidx.coordinatorlayout.widget.CoordinatorLayout>

**Comment by fantasticrahulrai** [comment]
Here it is dear my activity is coordinate layout only...can you share the sceenshot or code snipets of your main module of which the lib is a part

**Comment by lapism** [comment]
Ok. That is a bug probably. Give me a minute and I am going to release fixed version. I hope it will be fixed. We will see.

**Comment by fantasticrahulrai** [comment]
Yes dear, great support form you. Thanks a lot

**Comment by lapism** [comment]
2.1.3 is out. But it has been build with AS 4.1. I hope I will not be a problem.

**Comment by fantasticrahulrai** [comment]
No dear thats not a problem, I will test it and will let you know the result.

**Comment by lapism** [comment]
And I found another bug. You must add  android:stateListAnimator="@null"  to AppBarLayout for now.
